---
language: node_js
node_js:
  - "4"
  - "6"
  - "7"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - ember try:each
  - npm install bower
  - node node-tests/blueprint-tests.js
