name: CI

on:
  push:
    branches:
      - main
      - master
      - 'v*'
  pull_request: {}
  workflow_dispatch: 

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Run Ember Tests
        run: yarn test:ember
      - name: Run Node Tests
        run: yarn test:node

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --no-lockfile
      - name: Run Tests
        run: yarn test:ember
      - name: Run Node Tests
        run: yarn test:node

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.8
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - ember-default-with-jquery
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}

  typescript-compatibility:
    name: Type checking - ${{ matrix.typescript-scenario }}
    runs-on: ubuntu-latest
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        typescript-scenario:
          - typescript-4.2
          - typescript-4.3
          - typescript-4.4
          - typescript-4.5
          - typescript-next

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: volta-cli/action@v1
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Type checking
        run: ./node_modules/.bin/ember try:one --config-path="./config/ember-try-typescript.js" ${{ matrix.typescript-scenario }}
